---
- name: DuckDns setup
  hosts: "{{ variable_host | default('duck_dns') }}"

  tasks:
  - name: Creating DuckDns script
    lineinfile:
      path: ~/duckdns/duck.sh
      line: echo url="https://www.duckdns.org/update?domains={{ansible_env.DUCKDNS_SUBDOMAIN}}&token={{ansible_env.DUCKDNS_TOKEN}}&ip=" | curl -k -o ~/duckdns/duck.log -K -   
      mode: '700'
      create: yes

  - name: populate crontab with DuckDns script
    shell: | 
      crontab  << EOF
      */5 * * * * ~/duckdns/duck.sh >/dev/null 2>&1
      EOF

  - name: Run DuckDns script
    command: sh  ~/duckdns/duck.sh


# ================
#  PLAY number2
# ================

- name: Docker setup
  hosts: all
  become: yes
  tasks:
    - name: Apt Install base packages and update
      apt:
        name: [ "apt-transport-https ", "ca-certificates", "software-properties-common", "python3-pip"]
        update_cache: yes

    - name: install docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_users: 
            - "dishout"

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create Docker container
      community.general.docker_container:
        name: '{{ansible_env.CONTAINER_NAME}}'
        image: '{{ansible_env.DOCKER_IMAGE}}'
        ports:
          - '{{ansible_env.DOCKER_PORT}}'


